version: '3.8'

# Memobase 完整环境配置
# 包含 PostgreSQL + Redis + Memobase 服务器

services:
  # PostgreSQL 数据库
  memobase-postgres:
    image: postgres:15-alpine
    container_name: memobase_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-memobase}
      POSTGRES_USER: ${POSTGRES_USER:-memobase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-memobase_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    
    volumes:
      - memobase_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    
    networks:
      - memory_test_network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-memobase} -d ${POSTGRES_DB:-memobase}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存服务
  memobase-redis:
    image: redis:7-alpine
    container_name: memobase_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    
    volumes:
      - memobase_redis_data:/data
    
    networks:
      - memory_test_network
    
    restart: unless-stopped
    
    command: >
      redis-server 
      --appendonly yes 
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Memobase 主服务
  memobase-server:
    image: ghcr.io/memodb-io/memobase:latest
    container_name: memobase_server
    ports:
      - "8019:8000"
    
    env_file:
      - .env.memobase
    
    volumes:
      # 挂载配置文件
      - ./config.memobase.yaml:/app/config.yaml:ro
      - memobase_logs:/app/logs
    
    depends_on:
      memobase-postgres:
        condition: service_healthy
      memobase-redis:
        condition: service_healthy
    
    networks:
      - memory_test_network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8019/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Memobase 管理界面（可选）
  memobase-admin:
    image: adminer:latest
    container_name: memobase_admin
    ports:
      - "8081:8080"
    
    environment:
      ADMINER_DEFAULT_SERVER: memobase-postgres
      ADMINER_DESIGN: dracula
    
    depends_on:
      - memobase-postgres
    
    networks:
      - memory_test_network
    
    restart: unless-stopped

# 数据卷定义
volumes:
  memobase_postgres_data:
    driver: local
    name: ${VOLUME_PREFIX:-memory_test}_memobase_postgres_data
  
  memobase_redis_data:
    driver: local
    name: ${VOLUME_PREFIX:-memory_test}_memobase_redis_data
  
  memobase_logs:
    driver: local
    name: ${VOLUME_PREFIX:-memory_test}_memobase_logs

# 网络定义
networks:
  memory_test_network:
    name: ${DOCKER_NETWORK_NAME:-memory_test_network}
    driver: bridge
    external: false