# MemU Server Docker Compose Configuration
services:
  memu-server:
    image: memu:server-cpu
    container_name: memu-server
    restart: unless-stopped
    ports:
      - "31010:8000"
    env_file: ".env"
    volumes:
      # Persist memory data
      - memu-memory:/app/memory
      # Optional: mount logs
      - memu-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - memu-network

volumes:
  memu-memory:
    driver: local
  memu-logs:
    driver: local

networks:
  memu-network:
    driver: bridge
